// <auto-generated />
namespace Project_Managment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EditRegister8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditRegister8));
        
        string IMigrationMetadata.Id
        {
            get { return "201904251728531_EditRegister8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
